# Generated by Django 4.2.2 on 2023-06-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_detalle_costos_alter_detalle_id_servicio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estados',
            new_name='Estado',
        ),
        migrations.RenameModel(
            old_name='Historial',
            new_name='Historiale',
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
