# Generated by Django 4.2.2 on 2023-06-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_estados_estado_rename_historial_historiale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='costos',
            field=models.CharField(max_length=30, verbose_name='costos'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.servicio', verbose_name='id servicio'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_st',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.estado', verbose_name='id_st'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.CharField(max_length=30, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='descripcion equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tipo', verbose_name='id tipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario', verbose_name='id usuario'),
        ),
        migrations.AlterField(
            model_name='historiale',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.estado', verbose_name='id del estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=60, verbose_name='descripcion servicio'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='describir_pro',
            field=models.TextField(max_length=200, verbose_name='describir'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_entrega',
            field=models.DateField(verbose_name='fecha entrega'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_fin',
            field=models.DateField(verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_inicio',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='historiales_asignados', serialize=False, to='menu.usuario', verbose_name='id_usuario_c'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_realizados', to='menu.usuario', verbose_name='id_usuario_t'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='total',
            field=models.CharField(max_length=30, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.IntegerField(verbose_name='id_rol del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='telefono del usuario'),
        ),
    ]
