# Generated by Django 4.2.2 on 2023-06-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_detalle_costos_alter_detalle_id_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='id_servicio',
            field=models.IntegerField(verbose_name='id servicio'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_st',
            field=models.IntegerField(verbose_name='id_st'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_tipo',
            field=models.IntegerField(verbose_name='id tipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_usuario',
            field=models.IntegerField(verbose_name='id usuario'),
        ),
        migrations.AlterField(
            model_name='historiale',
            name='id_estado',
            field=models.IntegerField(verbose_name='id del estado'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_entrega',
            field=models.DateField(max_length=30, verbose_name='fecha entrega'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_fin',
            field=models.DateField(max_length=30, verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_inicio',
            field=models.DateField(max_length=30, verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_c',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id_usuario_c'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_t',
            field=models.IntegerField(verbose_name='id_usuario_t'),
        ),
    ]
