# Generated by Django 4.2.2 on 2023-06-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_detalle_id_servicio_alter_detalle_id_st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.servicio', verbose_name='id servicio'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_st',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.estado', verbose_name='id_st'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tipo', verbose_name='id tipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario', verbose_name='id usuario'),
        ),
        migrations.AlterField(
            model_name='historiale',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.estado', verbose_name='id del estado'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_entrega',
            field=models.DateField(verbose_name='fecha entrega'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_fin',
            field=models.DateField(verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='f_inicio',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='historiales_asignados', serialize=False, to='menu.usuario', verbose_name='id_usuario_c'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_usuario_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_realizados', to='menu.usuario', verbose_name='id_usuario_t'),
        ),
    ]
